/* By Kenzie Wright - SPDX-License-Identifier: Apache-2.0 */
/*! @file Hash.h

Provides offline and runtime hashing functions
*/
#pragma once

#include "Common.h"

#include "codegen/engine/utilities/Hash.h.gen.h"

/*! @brief Hash a constant string at compile time using the XXHash algorithm

    The string must be a fixed string initializer, no variables or nested macros
    Behind the scenes this marks a block of text to have its hash generated by
    the code generator and requires a file to include its "generated.h" file
*/
#define CT_XXH32_STRING(_identifier, _text) __CT_COMPILED_HASH_##_identifier

/*! @brief Hash the buffer using the XXHash algorithm */
uint32_t ctXXHash32Bytes(const void* buffer, size_t size);

/*! @brief Hash the string (excluding null-terminator) using the XXHash algorithm */
uint32_t ctXXHash32String(const char* string);